2019-03-18 13:25:11,915 ERROR 55843 [-/::1/-/7ms DELETE /api/user/1] nodejs.TypeError: Cannot destructure property `id` of 'undefined' or 'null'.
    at UserService.deleteUser (/Users/xiaohuangyu/work/egg-cms/app/service/admin/user.js:25:21)
    at UserController.destroy (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/user.js:28:50)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 55843
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 13:25:40,276 ERROR 55852 [-/::1/-/9ms DELETE /api/user/1] nodejs.TypeError: Cannot destructure property `id` of 'undefined' or 'null'.
    at UserService.deleteUser (/Users/xiaohuangyu/work/egg-cms/app/service/admin/user.js:25:21)
    at UserController.destroy (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/user.js:29:50)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 55852
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 13:42:55,820 ERROR 55924 [-/::1/-/33ms POST /api/auth] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `password` = '96e79218965eb72c92a549dd5a330112', `use` = 1 LIMIT 0, 1' at line 1
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_user` WHERE `where` = `username` = 'admin', `password` = '96e79218965eb72c92a549dd5a330112', `use` = 1 LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `password` = '96e79218965eb72c92a549dd5a330112', `use` = 1 LIMIT 0, 1' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `pme_user` WHERE `where` = `username` = 'admin', `password` = '96e79218965eb72c92a549dd5a330112', `use` = 1 LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 55924
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 16:07:47,926 ERROR 56314 [-/::1/-/5ms PUT /api/user/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'confirmPassword' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: UPDATE `pme_user` SET `username` = 'test', `password` = '698d51a19d8a121ce581499d7b701668', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'confirmPassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_user` SET `username` = 'test', `password` = '698d51a19d8a121ce581499d7b701668', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 56314
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 16:09:43,530 ERROR 56314 [-/::1/-/3ms PUT /api/user/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'confirmPassword' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'confirmPassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 56314
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 16:09:55,369 ERROR 56314 [-/::1/-/2ms PUT /api/user/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'confirmPassword' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'confirmPassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 56314
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 16:10:59,500 ERROR 56314 [-/::1/-/10ms PUT /api/user/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'confirmPassword' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'confirmPassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_user` SET `username` = 'test', `confirmPassword` = '', `nickname` = '213321fdsadgsfsdgfsdgf', `note` = 'fdsa432432' WHERE `id` = 2"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 56314
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 16:29:31,149 ERROR 58626 [-/::1/-/21ms PUT /api/user/3] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'confirmPassword' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: UPDATE `pme_user` SET `username` = 'fdsafdsa', `password` = '698d51a19d8a121ce581499d7b701668', `confirmPassword` = '111', `nickname` = NULL, `note` = NULL WHERE `id` = 3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'confirmPassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_user` SET `username` = 'fdsafdsa', `password` = '698d51a19d8a121ce581499d7b701668', `confirmPassword` = '111', `nickname` = NULL, `note` = NULL WHERE `id` = 3"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 58626
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 19:49:44,663 ERROR 60170 [-/::1/-/9ms GET /api/cat] nodejs.TypeError: this.service is not a function
    at CatController.index (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:12:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60170
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 19:52:20,694 ERROR 60174 [-/::1/-/7ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<CatController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:8:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60174
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 19:53:36,792 ERROR 60182 [-/::1/-/7ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<CatController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:8:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60182
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 19:54:11,020 ERROR 60184 [-/::1/-/7ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<CatController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:8:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60184
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 19:57:00,686 ERROR 60188 [-/::1/-/8ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<CatController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:8:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60188
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 10:32:42,735 ERROR 60481 [-/::1/-/7ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<BaseController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new BaseController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/base.js:8:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:9:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60481
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 10:34:02,399 ERROR 60486 [-/::1/-/8ms GET /api/cat] nodejs.TypeError: this.service is not a function
    at CatController.index (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:12:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60486
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 10:36:38,858 ERROR 60489 [-/::1/-/8ms GET /api/cat] nodejs.TypeError: Cannot set property service of #<BaseController> which has only a getter
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/base_context_class.js:35:18)
    at new BaseContextClass (/Users/xiaohuangyu/work/egg-cms/node_modules/egg/lib/core/base_context_class.js:13:1)
    at new BaseController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/base.js:8:1)
    at new CatController (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:9:1)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:83:26)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60489
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 10:39:33,941 ERROR 60499 [-/::1/-/7ms GET /api/cat] nodejs.TypeError: this.service.list is not a function
    at CatController.index (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/cat.js:11:34)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60499
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 11:15:50,970 ERROR 60590 [-/::1/-/14ms GET /api/cat] nodejs.TypeError: Cannot read property 'tokenSign' of undefined
    at auth (/Users/xiaohuangyu/work/egg-cms/app/middleware/auth.js:7:42)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 60590
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-19 11:26:31,628 ERROR 60650 [-/::1/-/48ms GET /api/cat] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'pme.pme__user' doesn't exist
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:55:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme__user` ORDER BY `sorter` DESC
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'pme.pme__user' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `pme__user` ORDER BY `sorter` DESC"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 60650
hostname: xiaohuangyudeMacBook-Pro.local

